[package]
name = "actionpack_rust"
version = "0.1.0"
edition = "2021"
authors = ["TODO: Write your name <TODO: Write your email address>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
